//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace cardOfClinic.Entity {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("historia_choroby", Namespace="", IsNullable=false)]
    public partial class Historia {
        
        private string poradniaField;
        
        private Dane_pacjenta pacjentField;
        
        private string podstawa_ubezpieczeniaField;
        
        private string komentarzField;
        
        private AuthorizedUpowazniony[] authorisedField;
        
        private ChorobyChoroba[] wywiadField;
        
        private decimal nr_kartyField;
        
        private System.DateTime data_zarejestrowaniaField;
        
        private bool data_zarejestrowaniaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string poradnia {
            get {
                return this.poradniaField;
            }
            set {
                this.poradniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dane_pacjenta pacjent {
            get {
                return this.pacjentField;
            }
            set {
                this.pacjentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string podstawa_ubezpieczenia {
            get {
                return this.podstawa_ubezpieczeniaField;
            }
            set {
                this.podstawa_ubezpieczeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string komentarz {
            get {
                return this.komentarzField;
            }
            set {
                this.komentarzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("upowazniony", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public AuthorizedUpowazniony[] authorised {
            get {
                return this.authorisedField;
            }
            set {
                this.authorisedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("choroba", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ChorobyChoroba[] wywiad {
            get {
                return this.wywiadField;
            }
            set {
                this.wywiadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal nr_karty {
            get {
                return this.nr_kartyField;
            }
            set {
                this.nr_kartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime data_zarejestrowania {
            get {
                return this.data_zarejestrowaniaField;
            }
            set {
                this.data_zarejestrowaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool data_zarejestrowaniaSpecified {
            get {
                return this.data_zarejestrowaniaFieldSpecified;
            }
            set {
                this.data_zarejestrowaniaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Dane_pacjenta {
        
        private string nazwiskoField;
        
        private string imieField;
        
        private System.DateTime data_urodzeniaField;
        
        private string telefonField;
        
        private AdresType adresField;
        
        private string peselField;
        
        private PlecType plecField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nazwisko {
            get {
                return this.nazwiskoField;
            }
            set {
                this.nazwiskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imie {
            get {
                return this.imieField;
            }
            set {
                this.imieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime data_urodzenia {
            get {
                return this.data_urodzeniaField;
            }
            set {
                this.data_urodzeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdresType adres {
            get {
                return this.adresField;
            }
            set {
                this.adresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pesel {
            get {
                return this.peselField;
            }
            set {
                this.peselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PlecType plec {
            get {
                return this.plecField;
            }
            set {
                this.plecField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdresType {
        
        private string ulicaField;
        
        private string numerField;
        
        private string kod_pocztowyField;
        
        private string miastoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ulica {
            get {
                return this.ulicaField;
            }
            set {
                this.ulicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numer {
            get {
                return this.numerField;
            }
            set {
                this.numerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kod_pocztowy {
            get {
                return this.kod_pocztowyField;
            }
            set {
                this.kod_pocztowyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string miasto {
            get {
                return this.miastoField;
            }
            set {
                this.miastoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PlecType {
        
        /// <remarks/>
        kobieta,
        
        /// <remarks/>
        mezczyzna,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AuthorizedUpowazniony {
        
        private string imie_nazwiskoField;
        
        private AdresType adres_upowaznionegoField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string nr_telefonuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imie_nazwisko {
            get {
                return this.imie_nazwiskoField;
            }
            set {
                this.imie_nazwiskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdresType adres_upowaznionego {
            get {
                return this.adres_upowaznionegoField;
            }
            set {
                this.adres_upowaznionegoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data_urodz_upowazn", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("nr_dowodu", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("pesel", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nr_telefonu {
            get {
                return this.nr_telefonuField;
            }
            set {
                this.nr_telefonuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        data_urodz_upowazn,
        
        /// <remarks/>
        nr_dowodu,
        
        /// <remarks/>
        pesel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ChorobyChoroba {
        
        private System.DateTime data_wizytyField;
        
        private string rozpoznanie_icd10Field;
        
        private string rozpoznanieField;
        
        private string nazwisko_lekarzaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime data_wizyty {
            get {
                return this.data_wizytyField;
            }
            set {
                this.data_wizytyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rozpoznanie_icd10 {
            get {
                return this.rozpoznanie_icd10Field;
            }
            set {
                this.rozpoznanie_icd10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rozpoznanie {
            get {
                return this.rozpoznanieField;
            }
            set {
                this.rozpoznanieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nazwisko_lekarza {
            get {
                return this.nazwisko_lekarzaField;
            }
            set {
                this.nazwisko_lekarzaField = value;
            }
        }
    }
}
